version: "3"
services:
  docker-app:
    tty: true
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /src/app/node_modules
      - .:/src/app

  tests:
    restart: "no"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /src/app/node_modules
      - .:/src/app
    command: ["npm", "run", "test"]
